session_name: losacordes
windows:
- focus: 'true'
  layout: b6fe,124x33,0,0,1
  options:
    automatic-rename: false
  panes:
  - focus: 'true'
    shell_command: nvim
  start_directory: /home/pau/programacion/losacordes/template
  window_name: generator.py
- layout: b6ff,124x33,0,0,2
  options:
    automatic-rename: true
  panes:
  - focus: 'true'
    shell_command: yazi
  start_directory: /home/pau/programacion/losacordes
  window_name: yazi
- layout: b700,124x33,0,0,3
  options:
    automatic-rename: false
  panes:
  - focus: 'true'
    shell_command: nix run nixpkgs#live-server
  start_directory: /home/pau/programacion/losacordes
  window_name: live-server
