session_name: losacordes
windows:
- focus: 'true'
  layout: ad7e,125x40,0,0,1
  options:
    automatic-rename: false
  panes:
  - focus: 'true'
    shell_command: nvim
  start_directory: /home/pau/programacion/losacordes/template
  window_name: generator.py
- layout: ad7f,125x40,0,0,2
  options:
    automatic-rename: true
  panes:
  - focus: 'true'
    shell_command: yazi
  start_directory: /home/pau/programacion/losacordes/song-data
  window_name: yazi
- layout: ad80,125x40,0,0,3
  options:
    automatic-rename: false
  panes:
  - focus: 'true'
    shell_command: live-server
  start_directory: /home/pau/programacion/losacordes
  window_name: live-server
