session_name: nix
windows:
- layout: b6fe,124x33,0,0,1
  options:
    automatic-rename: false
  panes:
  - focus: 'true'
    shell_command: nvim
  start_directory: /home/pau/.nixos-config
  window_name: configuration.nix
- focus: 'true'
  layout: 50a3,124x33,0,0{55x33,0,0,2,68x33,56,0,3}
  options:
    automatic-rename: true
  panes:
  - focus: 'true'
    shell_command:
    - cd /home/pau/.nixos-config
    - ff
  - shell_command:
    - cd /home/pau/.nixos-config/config
    - yazi
  window_name: bash
