# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7570f0a1-79bc-496f-ac2f-6b7ce3376e80";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/557f0a04-d76c-4936-a601-70460382b8b8"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
